Time::DATE_FORMATS[:datetime_jp] = '%Y年 %m月 %d日 %H時 %M分'
Time::DATE_FORMATS[:datetime]    = '%Y/%m/%d %H:%M'
Time::DATE_FORMATS[:date_jp]     = '%Y年 %m月 %d日'
Time::DATE_FORMATS[:date]        = '%Y/%m/%d'
Time::DATE_FORMATS[:time_jp]     = '%H時 %M分 %S秒'
Time::DATE_FORMATS[:time]        = '%H:%M:%S'
